export const PERMISSIONS = {
  USER_READ_SELF: "USER_READ_SELF",
  USER_UPDATE_SELF: "USER_UPDATE_SELF",

  RECORD_CREATE: "RECORD_CREATE",
  RECORD_READ_OWN: "RECORD_READ_OWN",
  RECORD_UPDATE_OWN: "RECORD_UPDATE_OWN",
  RECORD_DELETE_OWN: "RECORD_DELETE_OWN",

  MANAGER_READ_ASSIGNED_USERS: "MANAGER_READ_ASSIGNED_USERS",
  MANAGER_MANAGE_ASSIGNED_USERS: "MANAGER_MANAGE_ASSIGNED_USERS",
  MANAGER_APPROVE_RECORD: "MANAGER_APPROVE_RECORD",

  ADMIN_READ_USERS: "ADMIN_READ_USERS",
  ADMIN_READ_RECORDS: "ADMIN_READ_RECORDS",
  ADMIN_CREATE_USER: "ADMIN_CREATE_USER",
  ADMIN_UPDATE_USER: "ADMIN_UPDATE_USER",
  ADMIN_DISABLE_USER: "ADMIN_DISABLE_USER",
  ADMIN_ASSIGN_ROLE: "ADMIN_ASSIGN_ROLE",
  ADMIN_ASSIGN_MANAGER: "ADMIN_ASSIGN_MANAGER",
  ADMIN_VIEW_AUDIT_LOGS: "ADMIN_VIEW_AUDIT_LOGS",
  ADMIN_MANAGE_SETTINGS: "ADMIN_MANAGE_SETTINGS",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
export type AppRole = "USER" | "MANAGER" | "ADMIN";

const USER_PERMISSIONS = [
  PERMISSIONS.USER_READ_SELF,
  PERMISSIONS.USER_UPDATE_SELF,
  PERMISSIONS.RECORD_CREATE,
  PERMISSIONS.RECORD_READ_OWN,
  PERMISSIONS.RECORD_UPDATE_OWN,
  PERMISSIONS.RECORD_DELETE_OWN,
] as const;

const MANAGER_PERMISSIONS = [
  ...USER_PERMISSIONS,
  PERMISSIONS.MANAGER_READ_ASSIGNED_USERS,
  PERMISSIONS.MANAGER_MANAGE_ASSIGNED_USERS,
  PERMISSIONS.MANAGER_APPROVE_RECORD,
] as const;

const ADMIN_PERMISSIONS = [
  ...USER_PERMISSIONS,
  PERMISSIONS.ADMIN_READ_USERS,
  PERMISSIONS.ADMIN_READ_RECORDS,
  PERMISSIONS.ADMIN_CREATE_USER,
  PERMISSIONS.ADMIN_UPDATE_USER,
  PERMISSIONS.ADMIN_DISABLE_USER,
  PERMISSIONS.ADMIN_ASSIGN_ROLE,
  PERMISSIONS.ADMIN_ASSIGN_MANAGER,
  PERMISSIONS.ADMIN_VIEW_AUDIT_LOGS,
  PERMISSIONS.ADMIN_MANAGE_SETTINGS,
] as const;

export const ROLE_PERMISSIONS: Readonly<Record<AppRole, ReadonlySet<Permission>>> = {
  USER: new Set<Permission>(USER_PERMISSIONS),
  MANAGER: new Set<Permission>(MANAGER_PERMISSIONS),
  ADMIN: new Set<Permission>(ADMIN_PERMISSIONS),
};

export function hasPermission(role: AppRole, permission: Permission): boolean {
  return ROLE_PERMISSIONS[role].has(permission);
}
