import Link from "next/link";
import { redirect } from "next/navigation";
import { AdminShell } from "@/components/admin/admin-shell";
import { requirePermission } from "@/server/permissions/guards";
import { PERMISSIONS } from "@/server/permissions/permissions";
import { createUserAction } from "@/server/services/admin-user-actions";

export default async function NewAdminUserPage() {
  let admin; try { admin = await requirePermission(PERMISSIONS.ADMIN_CREATE_USER); } catch { redirect("/dashboard"); }
  return <AdminShell user={admin}><div className="mb-5"><Link className="text-sm font-medium text-slate-600 underline-offset-4 hover:underline" href="/admin/users">← User management</Link></div><section className="max-w-2xl rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-semibold text-slate-950">Create account</h2><p className="mt-1 text-sm text-slate-500">Create a user with an explicit initial role, status, and password.</p><form action={createUserAction} className="mt-6 grid gap-4 sm:grid-cols-2"><label><span className="mb-1 block text-sm font-medium">First name</span><input required maxLength={100} name="firstName" className="w-full rounded-xl border border-slate-300 px-3 py-2" /></label><label><span className="mb-1 block text-sm font-medium">Last name</span><input required maxLength={100} name="lastName" className="w-full rounded-xl border border-slate-300 px-3 py-2" /></label><label className="sm:col-span-2"><span className="mb-1 block text-sm font-medium">Email</span><input required type="email" name="email" className="w-full rounded-xl border border-slate-300 px-3 py-2" /></label><label className="sm:col-span-2"><span className="mb-1 block text-sm font-medium">Initial password</span><input required type="password" minLength={12} maxLength={128} name="password" autoComplete="new-password" className="w-full rounded-xl border border-slate-300 px-3 py-2" /><span className="mt-1 block text-xs text-slate-500">At least 12 characters with upper/lowercase letters and a number.</span></label><label><span className="mb-1 block text-sm font-medium">Role</span><select name="role" defaultValue="USER" className="w-full rounded-xl border border-slate-300 px-3 py-2"><option>USER</option><option>MANAGER</option><option>ADMIN</option></select></label><label><span className="mb-1 block text-sm font-medium">Status</span><select name="status" defaultValue="ACTIVE" className="w-full rounded-xl border border-slate-300 px-3 py-2"><option>ACTIVE</option><option>INACTIVE</option><option>SUSPENDED</option></select></label><div className="sm:col-span-2"><button type="submit" className="dashboard-action-link">Create account</button></div></form></section></AdminShell>;
}
