import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { AdminShell } from "@/components/admin/admin-shell";
import { ConfirmSubmitButton } from "@/components/admin/confirm-submit-button";
import { requirePermission } from "@/server/permissions/guards";
import { PERMISSIONS } from "@/server/permissions/permissions";
import { getAdminUserDetail } from "@/server/services/admin-user.service";
import { assignManagerAction, changeUserRoleAction, changeUserStatusAction, removeManagerAction, updateUserProfileAction } from "@/server/services/admin-user-actions";

export default async function AdminUserDetailPage({ params, searchParams }: { params: Promise<{ userId: string }>; searchParams: Promise<{ saved?: string }> }) {
  const { userId } = await params;
  let admin; try { admin = await requirePermission(PERMISSIONS.ADMIN_READ_USERS); } catch { redirect("/dashboard"); }
  let detail; try { detail = await getAdminUserDetail(userId); } catch { notFound(); }
  const { user, managers } = detail; const query = await searchParams;
  return <AdminShell user={admin}><div className="mb-5"><Link className="text-sm font-medium text-slate-600 underline-offset-4 hover:underline" href="/admin/users">← User management</Link></div>{query.saved && <div className="mb-5 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-900">Changes saved.</div>}<div className="grid gap-6 lg:grid-cols-2">
    <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-semibold text-slate-950">Account profile</h2><p className="mt-1 text-sm text-slate-500">{user.email}</p><form action={updateUserProfileAction} className="mt-5 grid gap-4 sm:grid-cols-2"><input type="hidden" name="userId" value={user.id} /><label><span className="mb-1 block text-sm font-medium">First name</span><input required maxLength={100} name="firstName" defaultValue={user.firstName} className="w-full rounded-xl border border-slate-300 px-3 py-2" /></label><label><span className="mb-1 block text-sm font-medium">Last name</span><input required maxLength={100} name="lastName" defaultValue={user.lastName} className="w-full rounded-xl border border-slate-300 px-3 py-2" /></label><div className="sm:col-span-2"><button className="dashboard-action-link" type="submit">Save profile</button></div></form><dl className="mt-6 grid gap-3 text-sm sm:grid-cols-2"><div><dt className="text-slate-500">Created</dt><dd className="font-medium text-slate-900">{user.createdAt.toLocaleString()}</dd></div><div><dt className="text-slate-500">Email verification</dt><dd className="font-medium text-slate-900">{user.emailVerified ? "Verified" : "Pending"}</dd></div></dl></section>
    <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-semibold text-slate-950">Access controls</h2><p className="mt-1 text-sm text-slate-500">Role and status changes invalidate existing sessions.</p><form action={changeUserRoleAction} className="mt-5 flex gap-3"><input type="hidden" name="userId" value={user.id} /><select name="role" defaultValue={user.role} className="min-w-0 flex-1 rounded-xl border border-slate-300 px-3 py-2"><option>USER</option><option>MANAGER</option><option>ADMIN</option></select><ConfirmSubmitButton message="Change this account role? Existing sessions will be invalidated.">Change role</ConfirmSubmitButton></form><form action={changeUserStatusAction} className="mt-4 flex gap-3"><input type="hidden" name="userId" value={user.id} /><select name="status" defaultValue={user.status} className="min-w-0 flex-1 rounded-xl border border-slate-300 px-3 py-2"><option>ACTIVE</option><option>INACTIVE</option><option>SUSPENDED</option></select><ConfirmSubmitButton message="Change this account status? Existing sessions will be invalidated.">Change status</ConfirmSubmitButton></form><p className="mt-5 text-xs leading-5 text-slate-500">Self-demotion, self-disable, and removal of the final active administrator are blocked on the server.</p></section>
  </div>
  {user.role === "USER" && <section className="mt-6 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-semibold text-slate-950">Manager assignments</h2><p className="mt-1 text-sm text-slate-500">Only active MANAGER accounts may be assigned to USER accounts.</p><form action={assignManagerAction} className="mt-5 flex max-w-xl gap-3"><input type="hidden" name="userId" value={user.id} /><select required name="managerId" defaultValue="" className="min-w-0 flex-1 rounded-xl border border-slate-300 px-3 py-2"><option value="" disabled>Select active manager</option>{managers.map((manager) => <option key={manager.id} value={manager.id}>{manager.firstName} {manager.lastName} — {manager.email}</option>)}</select><button className="dashboard-action-link" type="submit">Assign</button></form><div className="mt-5 space-y-3">{user.managerAssignments.length === 0 ? <p className="text-sm text-slate-500">No manager assignments.</p> : user.managerAssignments.map((assignment) => <div key={assignment.manager.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-slate-200 p-4"><div><p className="font-medium text-slate-950">{assignment.manager.firstName} {assignment.manager.lastName}</p><p className="text-sm text-slate-500">{assignment.manager.email}</p></div><form action={removeManagerAction}><input type="hidden" name="userId" value={user.id} /><input type="hidden" name="managerId" value={assignment.manager.id} /><ConfirmSubmitButton className="text-sm font-medium text-red-700 underline-offset-4 hover:underline" message="Remove this manager assignment?">Remove</ConfirmSubmitButton></form></div>)}</div></section>}
  {user.role === "MANAGER" && <section className="mt-6 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-semibold text-slate-950">Assigned users</h2><p className="mt-1 text-sm text-slate-500">Showing up to 50 explicit assignments.</p><div className="mt-5 space-y-3">{user.userAssignments.length === 0 ? <p className="text-sm text-slate-500">No assigned users.</p> : user.userAssignments.map((assignment) => <Link key={assignment.user.id} href={`/admin/users/${assignment.user.id}`} className="block rounded-xl border border-slate-200 p-4 hover:bg-slate-50"><p className="font-medium text-slate-950">{assignment.user.firstName} {assignment.user.lastName}</p><p className="mt-1 text-sm text-slate-500">{assignment.user.email} · {assignment.user.status}</p></Link>)}</div></section>}
  </AdminShell>;
}
